Repository 8-Sprinters/ListyWave-front, pull requests merged in 2024-06, with the labels that each got.

#241 Refactor: refreshToken 만료시간 재설정
  src/app/auth/redirect/kakao/page.tsx
  src/components/login/LoginModal.tsx
  src/lib/axios/axiosInstance.ts
  src/lib/utils/cookie.ts
  src/store/useUser.ts
Labels: Feat

#245 Feat: 개인정보 처리방침 페이지 연결 추가
  src/app/intro/_components/Footer.tsx
  src/app/intro/locale.ts
Labels: Feat, Docs

#246 fix: 콜렉션 페이지 bottom nav에 가려지는 하단부 여백 추가
  src/app/collection/page.css.ts
  src/app/collection/page.tsx
Labels: Fix

#243 Refactor: SEO 개선 작업 진행 (metadata, sitemap, robots.txt)
  src/app/layout.tsx
  src/app/list/[listId]/page.tsx
  src/app/robots.ts
  src/app/sitemap.ts
  src/app/user/[userId]/collabolist/page.tsx
  src/app/user/[userId]/mylist/page.tsx
  src/lib/constants/domain.ts
  src/lib/constants/metadata.ts
Labels: Refactor, Seo
