Repository 8-Sprinters/ListyWave-front, pull requests merged in 2024-02, with the labels that each got.

#8 Feat: husky 환경 설정 및 github autoassign 등록
  .eslintrc.json
  .github/auto_assign.yml
  .husky/_/.gitignore
  .husky/_/husky.sh
  .husky/commit-msg
  .husky/pre-commit
  .prettierrc
  commitlint.config.js
  package.json
  src/app/layout.tsx
  yarn.lock
Labels: Feat

#13 Feat: 리스트 아이템 구현 및 리스트 생성 페이지 합체
  .vscode/settings.json
  next.config.js
  package.json
  public/icons/add.svg
  public/icons/attach_image.svg
  public/icons/back.svg
  public/icons/clear_x_black.svg
  public/icons/clear_x_gray.svg
  public/icons/dnd.svg
  public/icons/link.svg
  src/app/create/_components/AddItemButton.css.ts
  src/app/create/_components/AddItemButton.tsx
  src/app/create/_components/CreateItem.css.ts
  src/app/create/_components/CreateItem.tsx
  src/app/create/_components/CreateList.tsx
  src/app/create/_components/ItemLayout.css.ts
  src/app/create/_components/ItemLayout.tsx
  src/app/create/_components/Items.css.ts
  src/app/create/_components/Items.tsx
  src/app/create/_components/LinkModal.tsx
  src/app/create/_components/LinkPreview.css.ts
  src/app/create/_components/LinkPreview.tsx
  src/app/create/page.tsx
  src/app/layout.tsx
  src/components/Label/Label.css.ts
  src/components/Label/Label.tsx
  src/components/Modal/Modal.css.ts
  src/components/Modal/Modal.tsx
  src/components/Modal/ModalButton.css.ts
  src/components/Modal/ModalButton.tsx
  src/components/Modal/ModalTitle.css.ts
  src/components/Modal/ModalTitle.tsx
  src/components/ModalPortal.ts
  src/components/StrictModeDroppable.tsx
  src/components/init.ts
  src/hooks/useBooleanOutput.ts
  src/hooks/useOnClickOutside.ts
  src/lib/constants/formInputValidationRules.ts
  src/lib/constants/placeholder.ts
  src/lib/constants/regExpressions.ts
  src/styles/globalStyles.css.ts
  yarn.lock
Labels: Feat

#11 Feat: 공용 모달 컴포넌트 추가
  src/components/ModalPortal.ts
  src/hooks/useBooleanOutput.ts
  src/hooks/useOnClickOutside.ts
Labels: Feat, Design

#10 Feat: 마이리스트, 콜라보리스트 페이지 구현
  package.json
  public/icons/arrow_left.svg
  public/icons/arrow_up.svg
  public/icons/lock_alt.svg
  public/icons/plus.svg
  public/icons/setting.svg
  src/app/[userNickname]/_components/Action.css.ts
  src/app/[userNickname]/_components/Action.tsx
  src/app/[userNickname]/_components/Card.css.ts
  src/app/[userNickname]/_components/Card.tsx
  src/app/[userNickname]/_components/CardItem.css.ts
  src/app/[userNickname]/_components/CardItem.tsx
  src/app/[userNickname]/_components/Categories.css.ts
  src/app/[userNickname]/_components/Categories.tsx
  src/app/[userNickname]/_components/Content.css.ts
  src/app/[userNickname]/_components/Content.tsx
  src/app/[userNickname]/_components/Profile.css.ts
  src/app/[userNickname]/_components/Profile.tsx
  src/app/[userNickname]/collabolist/page.tsx
  src/app/[userNickname]/mockData/categories.ts
  src/app/[userNickname]/mockData/items.ts
  src/app/[userNickname]/mockData/lists.ts
  src/app/[userNickname]/mockData/mockDataTypes.ts
  src/app/[userNickname]/mockData/user.ts
  src/app/[userNickname]/mylist/page.tsx
  src/app/_api/category/getCategories.ts
  src/app/_api/init.ts
  src/app/_api/list/createList.ts
  src/app/_api/list/deleteList.ts
  src/app/_api/list/getLists.ts
  src/app/layout.tsx
  src/components/floatingButton/ArrowUpFloatingButton.tsx
  src/components/floatingButton/FloatingContainer.css.ts
  src/components/floatingButton/FloatingContainer.tsx
  src/components/floatingButton/PlusOptionFloatingButton.tsx
  src/hooks/useThrottle.ts
  src/lib/axios/axiosInstance.ts
  src/lib/constants/queryKeys.ts
  src/lib/types/categoriesType.ts
  src/lib/types/commentType.ts
  src/lib/types/init.ts
  src/lib/types/listType.ts
  yarn.lock
Labels: Feat, Design

#14 Feat: 리스트 상세페이지 바깥쪽 레이아웃 퍼블리싱
  .eslintrc.json
  .github/workflows/Dev-CD.yml
  .gitignore
  .vscode/settings.json
  public/icons/cancel_button.svg
  public/icons/check_red.svg
  public/icons/clear.svg
  public/icons/collaborators_plus.svg
  public/icons/default_profile_temporary.svg
  public/icons/history.svg
  public/icons/horizontal_line.svg
  public/icons/trash_can.svg
  public/icons/vertical_kebab_button.svg
  settings.json
  src/app/[userNickname]/[listId]/ListDetail.css.ts
  src/app/[userNickname]/[listId]/_components/BottomSheet/BottomSheet.css.ts
  src/app/[userNickname]/[listId]/_components/BottomSheet/BottomSheet.tsx
  src/app/[userNickname]/[listId]/_components/ListDetailOuter/Collaborators.css.ts
  src/app/[userNickname]/[listId]/_components/ListDetailOuter/Collaborators.tsx
  src/app/[userNickname]/[listId]/_components/ListDetailOuter/CollaboratorsPopOver.css.ts
  src/app/[userNickname]/[listId]/_components/ListDetailOuter/CollaboratorsPopOver.tsx
  src/app/[userNickname]/[listId]/_components/ListDetailOuter/Comment.css.ts
  src/app/[userNickname]/[listId]/_components/ListDetailOuter/Comment.tsx
  src/app/[userNickname]/[listId]/_components/ListDetailOuter/Comments.css.ts
  src/app/[userNickname]/[listId]/_components/ListDetailOuter/Comments.tsx
  src/app/[userNickname]/[listId]/_components/ListDetailOuter/DeleteModalButton.tsx
  src/app/[userNickname]/[listId]/_components/ListDetailOuter/Header.css.ts
  src/app/[userNickname]/[listId]/_components/ListDetailOuter/Header.tsx
  src/app/[userNickname]/[listId]/_components/ListDetailOuter/ListInformation.css.ts
  src/app/[userNickname]/[listId]/_components/ListDetailOuter/ListInformation.tsx
  src/app/[userNickname]/[listId]/_components/ListDetailOuter/ModalButtonStyle.css.ts
  src/app/[userNickname]/[listId]/_components/ListDetailOuter/OpenBottomSheetButton.tsx
  src/app/[userNickname]/[listId]/_components/ListDetailOuter/PopOverMenu.css.ts
  src/app/[userNickname]/[listId]/_components/ListDetailOuter/PopOverMenu.tsx
  src/app/[userNickname]/[listId]/_components/ListDetailOuter/Replies.css.ts
  src/app/[userNickname]/[listId]/_components/ListDetailOuter/Replies.tsx
  src/app/[userNickname]/[listId]/mockData/mockdata.ts
  src/app/[userNickname]/[listId]/mockData/mockdataType.ts
  src/app/[userNickname]/[listId]/page.tsx
  src/app/page.tsx
  src/components/Label/Label.css.ts
  src/components/Label/Label.tsx
  src/hooks/init.ts
  src/lib/utils/init.ts
  src/lib/utils/timeDiff.ts
  src/styles/Pretendard-Black.woff2
  src/styles/Pretendard-Bold.woff2
  src/styles/Pretendard-ExtraBold.woff2
  src/styles/Pretendard-ExtraLight.woff2
  src/styles/Pretendard-Light.woff2
  src/styles/Pretendard-Medium.woff2
  src/styles/Pretendard-Regular.woff2
  src/styles/Pretendard-SemiBold.woff2
  src/styles/Pretendard-Thin.woff2
  tsconfig.json
  yarn.lock
Labels: Feat, Design

#16 Feat : 리스트 생성 페이지 구현 및 API 연결
  .env
  src/app/[userNickname]/collabolist/page.tsx
  src/app/[userNickname]/mylist/page.tsx
  src/app/_api/category/getCategories.ts
  src/app/_api/list/createList.ts
  src/app/_api/user/getUsers.ts
  src/app/create/_components/CreateItem.tsx
  src/app/create/_components/CreateList.css.ts
  src/app/create/_components/CreateList.tsx
  src/app/create/_components/item/AddItemButton.css.ts
  src/app/create/_components/item/AddItemButton.tsx
  src/app/create/_components/item/ItemLayout.css.ts
  src/app/create/_components/item/ItemLayout.tsx
  src/app/create/_components/item/Items.css.ts
  src/app/create/_components/item/Items.tsx
  src/app/create/_components/item/LinkModal.tsx
  src/app/create/_components/item/LinkPreview.css.ts
  src/app/create/_components/item/LinkPreview.tsx
  src/app/create/_components/list/ButtonSelector.css.ts
  src/app/create/_components/list/ButtonSelector.tsx
  src/app/create/_components/list/ColorSelector.css.ts
  src/app/create/_components/list/ColorSelector.tsx
  src/app/create/_components/list/CreateListMock.ts
  src/app/create/_components/list/Header.css.ts
  src/app/create/_components/list/Header.tsx
  src/app/create/_components/list/LabelInput.css.ts
  src/app/create/_components/list/LabelInput.tsx
  src/app/create/_components/list/MemberSelector.css.ts
  src/app/create/_components/list/MemberSelector.tsx
  src/app/create/_components/list/RadioInput.css.ts
  src/app/create/_components/list/RadioInput.tsx
  src/app/create/_components/list/Section.css.ts
  src/app/create/_components/list/Section.tsx
  src/app/create/_components/list/SimpleInput.css.ts
  src/app/create/_components/list/SimpleInput.tsx
  src/app/create/page.tsx
  src/app/layout.tsx
  src/lib/constants/formInputValidationRules.ts
  src/lib/constants/placeholder.ts
  src/lib/types/categoriesType.ts
  src/lib/types/listType.ts
  src/lib/types/userProfileType.ts
  src/styles/Color.ts
  src/styles/GlobalStyles.css.ts
Labels: Feat

#17 Feat: 이미지 첨부 기능 구현 및 리스트 생성 제출 API 연동
  package.json
  src/app/_api/list/createList.ts
  src/app/_api/list/uploadItemImages.ts
  src/app/create/_components/CreateItem.css.ts
  src/app/create/_components/CreateItem.tsx
  src/app/create/_components/CreateList.tsx
  src/app/create/_components/item/Header.css.ts
  src/app/create/_components/item/Header.tsx
  src/app/create/_components/item/ImageUploader.css.ts
  src/app/create/_components/item/ImageUploader.tsx
  src/app/create/_components/item/ItemLayout.tsx
  src/app/create/_components/item/Items.css.ts
  src/app/create/_components/item/Items.tsx
  src/app/create/_components/item/Preview.css.ts
  src/app/create/_components/item/Preview.tsx
  src/app/create/_components/list/Header.tsx
  src/app/create/page.tsx
  src/lib/constants/formInputValidationRules.ts
  src/lib/constants/queryKeys.ts
  src/lib/types/listType.ts
  yarn.lock
Labels: Feat, Refactor

#18 HOTFIX: 리스트생성 imageUrl 미삽입으로 인한 에러 해결 및 기타 수정
  public/icons/dnd.svg
  src/app/create/_components/CreateItem.tsx
  src/app/create/_components/item/ItemLayout.css.ts
  src/app/create/_components/item/ItemLayout.tsx
  src/app/create/_components/item/Items.css.ts
  src/app/create/_components/item/Items.tsx
  src/app/create/page.tsx
  src/app/user/[userId]/list/[listId]/page.tsx
  src/lib/types/listType.ts
  src/lib/utils/toasting.ts
  yarn.lock
Labels: Feat, Fix

#21 Feat: 마이리스트, 콜라보리스트 페이지 api 연동
  public/icons/arrow_left.svg
  public/icons/blue_line.svg
  public/icons/blue_line_long.svg
  src/app/[userNickname]/_components/CardItem.css.ts
  src/app/[userNickname]/_components/CardItem.tsx
  src/app/[userNickname]/_components/Categories.tsx
  src/app/[userNickname]/_components/Content.tsx
  src/app/[userNickname]/_components/Profile.tsx
  src/app/[userNickname]/mockData/categories.ts
  src/app/[userNickname]/mockData/items.ts
  src/app/[userNickname]/mockData/lists.ts
  src/app/[userNickname]/mockData/mockDataTypes.ts
  src/app/[userNickname]/mockData/user.ts
  src/app/[userNickname]/mylist/page.tsx
  src/app/_api/list/getAllList.ts
  src/app/_api/list/getLists.ts
  src/app/_api/user/getUserOne.ts
  src/app/account/page.tsx
  src/app/user/[userId]/_components/Card.css.ts
  src/app/user/[userId]/_components/Card.tsx
  src/app/user/[userId]/_components/Categories.css.ts
  src/app/user/[userId]/_components/Categories.tsx
  src/app/user/[userId]/_components/Content.css.ts
  src/app/user/[userId]/_components/Content.tsx
  src/app/user/[userId]/_components/FollowButton.css.ts
  src/app/user/[userId]/_components/FollowButton.tsx
  src/app/user/[userId]/_components/Profile.css.ts
  src/app/user/[userId]/_components/Profile.tsx
  src/app/user/[userId]/collabolist/page.tsx
  src/app/user/[userId]/followers/page.tsx
  src/app/user/[userId]/followings/page.tsx
  src/app/user/[userId]/mylist/page.tsx
  src/hooks/useMoveToPage.ts
  src/lib/constants/queryKeys.ts
  src/lib/types/listType.ts
  src/lib/types/userProfileType.ts
  tsconfig.json
Labels: Feat, Design, Style

#23 Feat: 카카오 OAuth 로그인 기능 구현
  src/app/auth/redirect/kakao/page.tsx
  src/app/login/_components/init.ts
  src/app/login/page.tsx
  src/lib/axios/axiosInstance.ts
  src/lib/types/user.ts
  src/store/useUser.ts
  tsconfig.json
Labels: Feat

#24 Feat: 마이리스트, 콜라보리스트 페이지 전체 리스트 조회 무한스크롤 구현
  src/app/_api/list/getAllList.ts
  src/app/user/[userId]/_components/Card.css.ts
  src/app/user/[userId]/_components/Card.tsx
  src/app/user/[userId]/_components/Categories.css.ts
  src/app/user/[userId]/_components/Categories.tsx
  src/app/user/[userId]/_components/Content.css.ts
  src/app/user/[userId]/_components/Content.tsx
  src/app/user/[userId]/_components/FollowButton.css.ts
  src/app/user/[userId]/_components/Profile.css.ts
  src/hooks/useIntersectionObserver.ts
Labels: Feat, Design

#25 Feat: 탐색 페이지 퍼블리싱, 데이터 바인딩 (임시)
  .env
  package.json
  public/icons/bell.svg
  public/icons/close_x_gray.svg
  public/icons/logo.svg
  src/app/[userNickname]/[listId]/_components/ListDetailInner/Footer.tsx
  src/app/[userNickname]/[listId]/_components/ListDetailInner/RankList.tsx
  src/app/[userNickname]/[listId]/_components/ListDetailInner/index.tsx
  src/app/[userNickname]/[listId]/_components/ListDetailOuter/ListInformation.tsx
  src/app/_api/comment/createComment.ts
  src/app/_api/comment/createReply.ts
  src/app/_api/comment/deleteComment.ts
  src/app/_api/comment/deleteReply.ts
  src/app/_api/comment/getComments.ts
  src/app/_api/explore/getRecommendedLists.ts
  src/app/_api/explore/getRecommendedUsers.ts
  src/app/_api/explore/getTrendingLists.ts
  src/app/_api/list/getLists.ts
  src/app/layout.css.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/components/KakaotalkShare/kakaotalkShare.tsx
  src/components/exploreComponents/Header.css.ts
  src/components/exploreComponents/Header.tsx
  src/components/exploreComponents/ListsRecommendation.css.ts
  src/components/exploreComponents/ListsRecommendation.tsx
  src/components/exploreComponents/TrendingLists.css.ts
  src/components/exploreComponents/TrendingLists.tsx
  src/components/exploreComponents/UsersRecommendation.css.ts
  src/components/exploreComponents/UsersRecommendation.tsx
  src/components/exploreComponents/_mockdata/mockdata.ts
  src/components/exploreComponents/_mockdata/mockdataType.ts
  src/lib/constants/queryKeys.ts
  src/lib/types/exploreType.ts
  src/lib/types/listType.ts
  yarn.lock
Labels: Feat, 추후 확인 필요

#28 HOTFIX: axiosInstance config에 Bearer 옵션 설정
  src/lib/axios/axiosInstance.ts
Labels: Fix

#26 Feat: 마이리스트, 콜라보리스트 페이지 팔로우 기능 구현
  src/app/[userNickname]/[listId]/_components/ListDetailInner/Footer.tsx
  src/app/_api/follow/createFollowUser.ts
  src/app/_api/follow/deleteFollowUser.ts
  src/app/_api/list/getAllList.ts
  src/app/_api/user/getUserOne.ts
  src/app/layout.tsx
  src/app/user/[userId]/_components/Card.tsx
  src/app/user/[userId]/_components/Content.tsx
  src/app/user/[userId]/_components/FollowButton.css.ts
  src/app/user/[userId]/_components/FollowButton.tsx
  src/app/user/[userId]/_components/Profile.tsx
  src/lib/constants/queryKeys.ts
  src/lib/constants/toastMessage.ts
  src/lib/utils/numberFormatter.ts
Labels: Feat, Design, Style

#30 Feat: 프로필 설정 페이지 구현 및 공용 폰트 업데이트
  .github/workflows/Dev-CD.yml
  package.json
  public/icons/camera.svg
  public/icons/error_x.svg
  src/app/_api/list/uploadItemImages.ts
  src/app/_api/user/checkNicknameDuplication.ts
  src/app/_api/user/updateProfile.ts
  src/app/account/page.tsx
  src/app/account/profile/_components/ImagePreview.css.ts
  src/app/account/profile/_components/ImagePreview.tsx
  src/app/account/profile/_components/ProfileForm.css.ts
  src/app/account/profile/_components/ProfileForm.tsx
  src/app/account/profile/page.tsx
  src/app/account/profile/styles.css.ts
  src/app/layout.tsx
  src/app/list/create/_components/item/ItemLayout.tsx
  src/app/list/create/_components/item/Items.css.ts
  src/app/list/create/_components/item/Items.tsx
  src/app/list/create/page.tsx
  src/components/BlueButton/BlueButton.css.ts
  src/components/BlueButton/BlueButton.tsx
  src/hooks/useBooleanOutput.ts
  src/hooks/useDebounce.ts
  src/hooks/useOnClickOutside.ts
  src/lib/constants/formInputValidationRules.ts
  src/lib/constants/init.ts
  src/lib/constants/placeholder.ts
  src/lib/constants/toastMessage.ts
  src/lib/types/userProfileType.ts
  src/lib/utils/compressFile.ts
  src/lib/utils/fileToBase64.ts
  src/lib/utils/saveImageFromHtml.ts
  src/styles/GlobalStyles.css.ts
  src/styles/font.css.ts
  src/styles/pretendard.css
  yarn.lock
Labels: Feat, Fix, Refactor, 추후 확인 필요

#34 Hotfix: 타입 에러 해결
  src/app/_api/explore/getRecommendedLists.ts
  src/app/_api/explore/getRecommendedUsers.ts
  src/app/_api/explore/getTrendingLists.ts
  src/app/account/profile/page.tsx
  src/app/user/[userId]/_components/FollowButton.tsx
  src/app/user/[userId]/list/[listId]/_components/ListDetailOuter/Comments.tsx
  src/components/exploreComponents/ListsRecommendation.tsx
  src/components/exploreComponents/UsersRecommendation.tsx
  src/components/exploreComponents/_mockdata/mockdata.ts
  src/components/exploreComponents/_mockdata/mockdataType.ts
  src/lib/types/exploreType.ts
Labels: Fix

#33 Feat: 로그인 모달 UI 구현
  public/icons/google_login.svg
  public/icons/kakao_login.svg
  public/icons/large_logo.svg
  public/icons/naver_login.svg
  src/app/login/_components/init.ts
  src/app/login/page.tsx
  src/components/Modal/Modal.css.ts
  src/components/Modal/Modal.tsx
  src/components/login/LoginModal.css.ts
  src/components/login/LoginModal.tsx
Labels: Feat, Design

#35 Feat: 로그아웃 기능 구현
  src/app/account/_components/LogoutModal.tsx
  src/app/account/page.tsx
  src/app/account/profile/page.tsx
  src/app/user/[userId]/_components/FollowButton.tsx
  src/app/user/[userId]/list/[listId]/_components/ListDetailOuter/Comments.tsx
  src/lib/constants/toastMessage.ts
  src/store/useUser.ts
Labels: Feat, Design

#36 Feat: 마이페이지 구현
  public/icons/globe.svg
  public/icons/help_circle.svg
  public/icons/logout.svg
  public/icons/message_square.svg
  public/icons/settings.svg
  public/icons/user.svg
  public/icons/withdraw_x.svg
  src/app/account/_components/LanguageDropdown.css.ts
  src/app/account/_components/LanguageDropdown.tsx
  src/app/account/page.tsx
  src/app/account/style.css.ts
  src/app/list/create/_components/item/LinkModal.tsx
  src/components/Header/Header.tsx
Labels: Feat, Fix, Design

#37 Feat: 하단 네비게이션(Bottom Nav) 컴포넌트 구현
  public/icons/collection.svg
  public/icons/explore.svg
  public/icons/my_feed.svg
  src/app/collection/page.tsx
  src/app/layout.tsx
  src/components/BottomNav/BottomNav.css.ts
  src/components/BottomNav/BottomNav.tsx
  src/components/floatingButton/FloatingContainer.css.ts
Labels: Feat, Design

#41 Refactor: 최대 430px로 레이아웃 수정, 하단 네브바 페이지별 노출 구분 처리, 모달 버튼 수정
  src/app/account/page.css.ts
  src/app/account/page.tsx
  src/app/account/profile/page.css.ts
  src/app/account/profile/page.tsx
  src/app/layout.css.ts
  src/app/layout.tsx
  src/app/list/create/_components/item/Items.css.ts
  src/app/page.css.ts
  src/app/page.tsx
  src/components/BottomNav/BottomNav.css.ts
  src/components/BottomNav/BottomNav.tsx
  src/components/Modal/Modal.css.ts
  src/components/Modal/Modal.tsx
  src/components/Modal/ModalButton.css.ts
  src/components/Modal/ModalSingleButton.tsx
  src/components/floatingButton/FloatingContainer.css.ts
  src/components/floatingButton/FloatingContainer.tsx
  src/styles/GlobalStyles.css.ts
  src/styles/theme.css.ts
Labels: Refactor, Design, Chore

#38 Feat: 팔로잉/팔로워 조회 페이지 API 연결 및 리스트 생성 페이지 유저 검색 API 연결 완료
  src/app/_api/follow/deleteFollower.ts
  src/app/_api/follow/getFollowerList.ts
  src/app/_api/follow/getFollowingList.ts
  src/app/_api/user/getUsersByNicknameSearch.ts
  src/app/list/create/_components/CreateList.tsx
  src/app/list/create/_components/list/MemberSelector.tsx
  src/app/user/[userId]/(follow)/_components/UserList.css.ts
  src/app/user/[userId]/(follow)/_components/UserList.tsx
  src/app/user/[userId]/(follow)/followers/page.tsx
  src/app/user/[userId]/(follow)/followings/page.tsx
  src/app/user/[userId]/list/[listId]/edit/page.tsx
  src/lib/constants/queryKeys.ts
  src/lib/types/followType.ts
  src/lib/types/user.ts
Labels: Feat, Fix, Design

#40 Feat: 탐색 페이지 팔로잉/팔로우 취소 로직 구현, 헤더 로직 구현, 무한스크롤, 사용자 추천 리스트, 리스트 추천 컴포넌트 디자인 수정,리팩토링
  public/icons/avatar.svg
  public/icons/chevron_right.svg
  public/icons/crown_new.svg
  public/images/no_data_image.svg
  src/app/_api/comment/createComment.ts
  src/app/_api/explore/getRecommendedLists.ts
  src/app/page.tsx
  src/app/user/[userId]/list/[listId]/_components/ListDetailOuter/Comments.tsx
  src/components/KakaotalkShare/kakaotalkShare.tsx
  src/components/Label/Label.css.ts
  src/components/Label/Label.tsx
  src/components/NoData/NoData.css.ts
  src/components/NoData/NoDataComponent.tsx
  src/components/SimpleList/SimpleList.css.ts
  src/components/SimpleList/SimpleList.tsx
  src/components/exploreComponents/FollowButton.tsx
  src/components/exploreComponents/Header.css.ts
  src/components/exploreComponents/Header.tsx
  src/components/exploreComponents/ListRecommendationSkeleton.tsx
  src/components/exploreComponents/ListsRecommendation.css.ts
  src/components/exploreComponents/ListsRecommendation.tsx
  src/components/exploreComponents/TrendingLists.css.ts
  src/components/exploreComponents/TrendingLists.tsx
  src/components/exploreComponents/UsersRecommendation.css.ts
  src/components/exploreComponents/UsersRecommendation.tsx
  src/lib/constants/exploreListBackgroundColor.ts
  src/lib/types/listType.ts
Labels: Feat, Fix, Refactor, Design, Style

#46 Hotfix: 탐색 no이미지 관련 오류 해결
  src/components/NoData/NoDataComponent.tsx
  src/components/SimpleList/SimpleList.tsx
  src/components/exploreComponents/ListsRecommendation.tsx
  src/components/exploreComponents/TrendingLists.tsx
  src/components/exploreComponents/UsersRecommendation.tsx
  src/lib/types/listType.ts
Labels: Fix

#47 리스트 수정페이지 완료 및 히스토리 퍼블리싱 완료
  public/icons/chevron_down_sm.svg
  public/icons/crown.svg
  public/icons/vertical_kebab_button.svg
  src/app/_api/history/getHistories.ts
  src/app/_api/list/updateList.ts
  src/app/list/create/_components/CreateItem.tsx
  src/app/list/create/_components/item/ImageUploader.tsx
  src/app/list/create/_components/item/ItemLayout.tsx
  src/app/list/create/_components/item/Items.tsx
  src/app/list/create/_components/list/MemberSelector.tsx
  src/app/list/create/page.tsx
  src/app/user/[userId]/list/[listId]/_components/ListDetailOuter/ModalButtonStyle.css.ts
  src/app/user/[userId]/list/[listId]/edit/page.tsx
  src/app/user/[userId]/list/[listId]/history/_component/HistoryGraph.css.ts
  src/app/user/[userId]/list/[listId]/history/_component/HistoryGraph.tsx
  src/app/user/[userId]/list/[listId]/history/_component/HistoryVersions.css.ts
  src/app/user/[userId]/list/[listId]/history/_component/HistoryVersions.tsx
  src/app/user/[userId]/list/[listId]/history/mock.json
  src/app/user/[userId]/list/[listId]/history/page.css.ts
  src/app/user/[userId]/list/[listId]/history/page.tsx
  src/lib/types/historyType.ts
  src/lib/types/listType.ts
  src/lib/types/user.ts
Labels: Feat

#51 히스토리 페이지 구현 완료 및 중간 QA 반영 및 404페이지
  package.json
  public/images/not-found.svg
  src/app/_api/history/deleteHistory.ts
  src/app/_api/history/toggleHistoryPulblic.ts
  src/app/_api/user/getUsersByNicknameSearch.ts
  src/app/list/create/_components/CreateList.css.ts
  src/app/list/create/_components/list/ColorSelector.css.ts
  src/app/list/create/_components/list/SimpleInput.tsx
  src/app/not-found.css.ts
  src/app/not-found.tsx
  src/app/user/[userId]/(follow)/_components/UserList.css.ts
  src/app/user/[userId]/(follow)/_components/UserList.tsx
  src/app/user/[userId]/(follow)/follow.css.ts
  src/app/user/[userId]/(follow)/followers/page.tsx
  src/app/user/[userId]/(follow)/followings/page.tsx
  src/app/user/[userId]/list/[listId]/_components/BottomSheet/BottomSheet.css.ts
  src/app/user/[userId]/list/[listId]/history/_component/HistoryGraph.css.ts
  src/app/user/[userId]/list/[listId]/history/_component/HistoryGraph.tsx
  src/app/user/[userId]/list/[listId]/history/_component/HistoryVersions.css.ts
  src/app/user/[userId]/list/[listId]/history/_component/HistoryVersions.tsx
  src/app/user/[userId]/list/[listId]/history/mock.json
  src/app/user/[userId]/list/[listId]/history/page.css.ts
  src/app/user/[userId]/list/[listId]/history/page.tsx
  src/lib/constants/queryKeys.ts
  tsconfig.json
  yarn.lock
Labels: Feat, Design

#50 refactor: 리스트생성 리팩토링
  public/icons/trash_bin.svg
  src/app/list/create/_components/CreateItem.css.ts
  src/app/list/create/_components/CreateItem.tsx
  src/app/list/create/_components/CreateList.css.ts
  src/app/list/create/_components/item/AddItemButton.css.ts
  src/app/list/create/_components/item/ImagePreview.tsx
  src/app/list/create/_components/item/ImageUploader.css.ts
  src/app/list/create/_components/item/ItemLayout.css.ts
  src/app/list/create/_components/item/ItemLayout.tsx
  src/app/list/create/_components/item/Items.css.ts
  src/app/list/create/_components/item/Items.tsx
  src/app/list/create/_components/item/LinkModal.css.ts
  src/app/list/create/_components/item/LinkModal.tsx
  src/app/list/create/_components/item/LinkPreview.tsx
  src/app/list/create/_components/item/Preview.tsx
  src/app/list/create/_components/list/ButtonSelector.css.ts
  src/app/list/create/_components/list/Header.tsx
  src/app/list/create/_components/list/LabelInput.css.ts
  src/app/list/create/_components/list/MemberSelector.css.ts
  src/app/list/create/_components/list/MemberSelector.tsx
  src/app/list/create/_components/list/RadioInput.css.ts
  src/app/list/create/_components/list/RadioInput.tsx
  src/app/list/create/_components/list/Section.css.ts
  src/app/list/create/_components/list/SimpleInput.css.ts
  src/app/list/create/_components/list/SimpleInput.tsx
  src/app/list/create/page.tsx
  src/components/BlueButton/BlueButton.css.ts
  src/components/Header/Header.css.ts
  src/hooks/useResizeTextarea.ts
Labels: Feat, Refactor, Design

#48 Feat : 트렌딩 리스트 디자인 수정 및 알림 확인 api 연동
  public/icons/notification_on.svg
  src/app/_api/explore/getNotificationAllChecked.ts
  src/components/NoData/NoDataComponent.tsx
  src/components/exploreComponents/Header.tsx
  src/components/exploreComponents/TrendingLists.css.ts
  src/components/exploreComponents/TrendingLists.tsx
  src/lib/constants/queryKeys.ts
  src/lib/constants/trendingListCustomStyle.ts
  src/lib/types/exploreType.ts
Labels: Feat, Design

#49 Feat: 댓글 답글 수정 기능 구현, 비회원 댓글 로직 구현, 모달& 바텀시트 등 바뀐 디자인 수정
  public/icons/edit_pen.svg
  public/icons/trash_can.svg
  src/app/_api/comment/EditComment.ts
  src/app/_api/comment/EditReply.ts
  src/app/_api/comment/createComment.ts
  src/app/_api/comment/createReply.ts
  src/app/_api/comment/deleteComment.ts
  src/app/_api/comment/deleteReply.ts
  src/app/_api/comment/getComments.ts
  src/app/_api/explore/getRecommendedLists.ts
  src/app/_api/explore/getRecommendedUsers.ts
  src/app/_api/explore/getTrendingLists.ts
  src/app/user/[userId]/list/[listId]/ListDetail.css.ts
  src/app/user/[userId]/list/[listId]/_components/BottomSheet/BottomSheet.css.ts
  src/app/user/[userId]/list/[listId]/_components/ListDetailOuter/Collaborators.css.ts
  src/app/user/[userId]/list/[listId]/_components/ListDetailOuter/Collaborators.tsx
  src/app/user/[userId]/list/[listId]/_components/ListDetailOuter/CollaboratorsPopOver.css.ts
  src/app/user/[userId]/list/[listId]/_components/ListDetailOuter/CollaboratorsPopOver.tsx
  src/app/user/[userId]/list/[listId]/_components/ListDetailOuter/Comment.css.ts
  src/app/user/[userId]/list/[listId]/_components/ListDetailOuter/Comment.tsx
  src/app/user/[userId]/list/[listId]/_components/ListDetailOuter/CommentForm.tsx
  src/app/user/[userId]/list/[listId]/_components/ListDetailOuter/Comments.css.ts
  src/app/user/[userId]/list/[listId]/_components/ListDetailOuter/Comments.tsx
  src/app/user/[userId]/list/[listId]/_components/ListDetailOuter/DeleteModalButton.tsx
  src/app/user/[userId]/list/[listId]/_components/ListDetailOuter/HeaderRight.tsx
  src/app/user/[userId]/list/[listId]/_components/ListDetailOuter/ListInformation.css.ts
  src/app/user/[userId]/list/[listId]/_components/ListDetailOuter/ListInformation.tsx
  src/app/user/[userId]/list/[listId]/_components/ListDetailOuter/OpenBottomSheetButton.tsx
  src/app/user/[userId]/list/[listId]/_components/ListDetailOuter/Replies.css.ts
  src/app/user/[userId]/list/[listId]/_components/ListDetailOuter/Replies.tsx
  src/components/Modal/Modal.css.ts
  src/hooks/useInfiniteScroll.ts
  src/lib/types/userProfileType.ts
  src/store/useComment.ts
Labels: Feat, Refactor, Design, Style

#52 Feat: 로그인 refreshToken 도입 및 인가 처리
  package.json
  src/app/account/_components/LogoutModal.tsx
  src/app/auth/redirect/kakao/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/user/[userId]/_components/FollowButton.tsx
  src/components/BottomNav/BottomNav.tsx
  src/lib/axios/axiosInstance.ts
  src/lib/constants/toastMessage.ts
  src/lib/types/user.ts
  src/lib/utils/cookie.ts
  src/middleware.ts
  yarn.lock
Labels: Feat

#45 Feat: floating button 기능 추가 및 mylist page 디자인 수정
  public/icons/blue_line.svg
  public/icons/blue_line_long.svg
  public/icons/share_alt.svg
  public/icons/write.svg
  src/app/user/[userId]/_components/Card.css.ts
  src/app/user/[userId]/_components/Card.tsx
  src/app/user/[userId]/_components/Categories.css.ts
  src/app/user/[userId]/_components/Categories.tsx
  src/app/user/[userId]/_components/CategoriesSkeleton.tsx
  src/app/user/[userId]/_components/Content.css.ts
  src/app/user/[userId]/_components/Content.tsx
  src/app/user/[userId]/_components/FollowButton.css.ts
  src/app/user/[userId]/_components/MasonryGridSkeleton.tsx
  src/app/user/[userId]/_components/Profile.css.ts
  src/app/user/[userId]/_components/Profile.tsx
  src/app/user/[userId]/_components/ProfileSkeleton.tsx
  src/app/user/[userId]/_components/SkeletonDesign.css.ts
  src/components/BottomNav/BottomNav.tsx
  src/components/floatingButton/ArrowUpFloatingButton.tsx
  src/components/floatingButton/FloatingContainer.css.ts
  src/components/floatingButton/PlusOptionFloatingButton.tsx
  src/styles/theme.css.ts
Labels: Feat, Refactor, Design

#59 Refactor: 리스트 생성
  src/app/_api/user/updateProfile.ts
  src/app/layout.css.ts
  src/app/layout.tsx
  src/app/list/[listId]/edit/page.tsx
  src/app/list/create/_components/CreateList.tsx
  src/app/list/create/_components/item/ItemLayout.tsx
  src/app/list/create/_components/item/Items.css.ts
  src/app/list/create/_components/item/Items.tsx
  src/app/list/create/_components/list/SimpleInput.tsx
  src/app/list/create/page.tsx
  src/lib/constants/toastMessage.ts
  src/lib/types/listType.ts
  src/lib/utils/toasting.ts
Labels: Refactor, Design

#60 Fix: 탐색 페이지, 리스트 상세 조회 페이지 UI 수정, 로직 수정
  package.json
  public/icons/chevron_down.svg
  src/app/list/[listId]/_components/ListDetailOuter/Collaborators.css.ts
  src/app/list/[listId]/_components/ListDetailOuter/CollaboratorsPopOver.css.ts
  src/app/list/[listId]/_components/ListDetailOuter/Comments.tsx
  src/app/list/[listId]/_components/ListDetailOuter/ListInformation.css.ts
  src/app/list/[listId]/_components/ListDetailOuter/ListInformation.tsx
  src/app/list/[listId]/_components/ListDetailOuter/Replies.css.ts
  src/app/page.css.ts
  src/app/page.tsx
  src/components/exploreComponents/FollowButton.tsx
  src/components/exploreComponents/Header.tsx
  src/components/exploreComponents/ListsRecommendation.css.ts
  src/components/exploreComponents/ListsRecommendation.tsx
  src/components/exploreComponents/TrendingLists.css.ts
  src/components/exploreComponents/TrendingLists.tsx
  src/components/exploreComponents/UsersRecommendation.css.ts
  src/components/exploreComponents/UsersRecommendation.tsx
  src/components/loading/Animation - 1708700954738.json
  src/components/loading/Loading.tsx
  src/lib/types/userProfileType.ts
  yarn.lock
Labels: Fix

#61 Refactor: 프로필 설정 페이지리팩토링
  public/icons/check_blue.svg
  src/app/_api/user/getDefaultBackgroundImages.ts
  src/app/_api/user/getDefaultProfileImages.ts
  src/app/_api/user/updateProfile.ts
  src/app/account/page.css.ts
  src/app/account/page.tsx
  src/app/account/profile/_components/ProfileForm.css.ts
  src/app/account/profile/_components/ProfileForm.tsx
  src/app/account/profile/_components/ProfileSkeleton.tsx
  src/app/account/profile/page.tsx
  src/hooks/useDebounce.ts
  src/lib/constants/queryKeys.ts
  src/lib/types/userProfileType.ts
  src/styles/GlobalStyles.css.ts
Labels: Fix, Refactor, Design

#63 Fix: 리스트상세 URL 변경에 따른 알림 클릭시 이동 경로 변경
  src/app/list/[listId]/_components/ListDetailOuter/Comments.tsx
  src/app/notification/_components/NotificationList.tsx
Labels: Fix

#67 HOTFIX: 리스트 생성 오류 수정
  src/app/layout.css.ts
  src/app/layout.tsx
  src/app/list/create/_components/CreateList.tsx
  src/app/list/create/_components/item/ItemLayout.css.ts
  src/app/list/create/_components/item/ItemLayout.tsx
  src/app/list/create/_components/item/Items.tsx
  src/app/list/create/_components/list/LabelInput.tsx
  src/lib/utils/toasting.ts
  src/styles/GlobalStyles.css.ts
Labels: Fix

#78 Refactor: 리스트 수정, 생성 페이지는 히스토리 기록에 남지 않도록 수정
  src/app/layout.tsx
  src/app/list/[listId]/edit/page.tsx
  src/app/list/create/page.tsx
Labels: Refactor, Enhance

#82 Fix: 리스트 수정 이미지 첨부 오류 해결
  public/images/ocean.png
  public/images/sparkle.png
  public/images/wave.png
  src/app/_api/list/updateList.ts
  src/app/list/[listId]/edit/page.tsx
  src/app/list/create/_components/CreateItem.tsx
  src/app/list/create/_components/item/ImageUploader.tsx
  src/app/list/create/_components/item/ItemLayout.tsx
  src/app/list/create/_components/item/Items.tsx
  src/app/list/create/_components/item/LinkPreview.tsx
  src/app/list/create/_components/list/LabelInput.tsx
Labels: Fix, Refactor

#86 Refactor: 아코디언 default 열림 상태, 메타 태그 재설정, 버튼 뒷 배경 없애기 재시도
  src/app/layout.tsx
  src/app/list/create/_components/item/ItemLayout.tsx
  src/styles/GlobalStyles.css.ts
Labels: Fix, Enhance

#87 Hotfix: 리스트 삭제 시, 마이 피드에 반영 안 되는 문제, 댓글 창 디자인 수정, 헤더 디자인 수정
  public/icons/airplane_send.svg
  public/icons/send.svg
  src/app/_api/list/deleteList.ts
  src/app/list/[listId]/_components/ListDetailOuter/CommentForm.tsx
  src/app/list/[listId]/_components/ListDetailOuter/Comments.css.ts
  src/app/list/[listId]/_components/ListDetailOuter/OpenBottomSheetButton.tsx
  src/components/exploreComponents/Header.css.ts
  src/components/exploreComponents/Header.tsx
  src/components/exploreComponents/ListsRecommendation.css.ts
  src/components/exploreComponents/ListsRecommendation.tsx
  src/components/exploreComponents/Skeleton.tsx
  src/components/exploreComponents/TrendingLists.css.ts
  src/components/exploreComponents/TrendingLists.tsx
  src/components/exploreComponents/UsersRecommendation.css.ts
  src/components/exploreComponents/UsersRecommendation.tsx
Labels: Fix, Enhance, Design

#89 Hotfix: 헤더 버그 수정
  src/components/exploreComponents/Header.tsx
Labels: Fix

#102 Hotfix/fix feed - QA반영 및 기능 관련 코드 수정
  src/app/_api/list/getAllList.ts
  src/app/auth/redirect/kakao/page.tsx
  src/app/page.tsx
  src/app/start-listy/_components/CreateNicknameStep.tsx
  src/app/start-listy/page.tsx
  src/app/user/[userId]/_components/Card.css.ts
  src/app/user/[userId]/_components/Content.css.ts
  src/app/user/[userId]/_components/Content.tsx
  src/app/user/[userId]/_components/FollowButton.tsx
  src/components/BottomNav/BottomNav.tsx
  src/components/exploreComponents/FollowButton.tsx
  src/components/floatingButton/PlusOptionFloatingButton.tsx
  src/lib/axios/axiosInstance.ts
Labels: Fix, Refactor

#121 Feat: Metadata, OG 추가
  src/app/_context/CommonProvider.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/opengraph-image.alt.txt
  src/app/opengraph-image.png
  src/app/user/[userId]/collabolist/page.tsx
  src/app/user/[userId]/mylist/page.tsx
Labels: Enhance

#126 Feat: 마이피드 접근 시, 에러 케이스(탈퇴 / 잘못된id 입력 / 없는 사용자)에 따른 에러처리 로직 추가
  src/app/user/[userId]/_components/Profile.tsx
Labels: Feat, Fix

#129 Feat: metadataBase URL 추가
  .env
  src/app/layout.tsx
Labels: Fix

#134 Hotfix: 비공개 게시물 히스토리 버튼 노출 안 되게 수정
  src/app/list/[listId]/_components/ListDetailOuter/HeaderRight.tsx
  src/app/list/[listId]/_components/ListDetailOuter/ListInformation.css.ts
  src/app/list/[listId]/_components/ListDetailOuter/ListInformation.tsx
Labels: Fix

#135 Hotfix/UI refactoring - 온보딩 페이지 일부 디자인 수정
  src/app/start-listy/_components/CreateListStep.tsx
  src/app/start-listy/_components/CreateNicknameStep.css.ts
  src/app/start-listy/_components/ListPreview.css.ts
Labels: Design

#138 Fix: 댓글 띄어쓰기만 되어도 작성되는 문제 해결, 인트로 페이지 UI 개선
  src/app/intro/_components/SearchBar.css.ts
  src/app/intro/_components/Section6.tsx
  src/app/list/[listId]/_components/ListDetailOuter/Comments.tsx
Labels: Fix

#151 Fix: 리스트 전체 조회 api 필드 값 변경으로 인한 타입, 쿼리 프로퍼티 수정
  src/app/_api/list/getAllList.ts
  src/app/user/[userId]/_components/Content.tsx
  src/lib/types/listType.ts
Labels: Fix

#155 Feature: 콜렉션 카테고리 폴더 퍼블리싱 및 구조 변경
  public/icons/folder_animal_plant.svg
  public/icons/folder_book.svg
  public/icons/folder_culture.svg
  public/icons/folder_entire.svg
  public/icons/folder_etc.svg
  public/icons/folder_life.svg
  public/icons/folder_movie_drama.svg
  public/icons/folder_music.svg
  public/icons/folder_place.svg
  src/app/_api/collect/getCollectionCategories.ts
  src/app/_api/user/withdraw.ts
  src/app/account/profile/_components/ProfileForm.css.ts
  src/app/account/profile/_components/ProfileForm.tsx
  src/app/account/withdraw/_component/WithdrawalButton.tsx
  src/app/collection/page.css.ts
  src/app/collection/page.tsx
  src/components/exploreComponents/TrendingLists.tsx
  src/lib/constants/queryKeys.ts
Labels: Feat, Design

#158 Fix: 리스트생성의 아이템 링크, 아코디언 & 팔로잉 목록 헤더 & 공용 프로필이미지 컴포넌트 오류 수정
  src/app/list/create/_components/item/ItemLayout.tsx
  src/app/list/create/_components/item/Items.css.ts
  src/app/list/create/_components/item/Items.tsx
  src/app/list/create/_components/item/LinkModal.css.ts
  src/app/list/create/_components/item/LinkModal.tsx
  src/app/user/[userId]/(follow)/_components/Header.tsx
  src/components/UserProfileImage/UserProfileImage.css.ts
  src/components/UserProfileImage/UserProfileImage.tsx
  src/lib/constants/placeholder.ts
Labels: Fix, Refactor

#159 HOTFIX: 링크 미리보기 연결 url 오류 해결
  src/app/list/create/_components/item/Items.tsx
  src/app/list/create/_components/item/LinkPreview.tsx
Labels: Fix

#160 Fix: 링크 정규식, 무한스크롤 개수
  src/app/_api/list/getAllList.ts
  src/app/list/create/_components/item/LinkModal.tsx
  src/lib/constants/formInputValidationRules.ts
  src/lib/constants/regExpressions.ts
Labels: Fix

#161 Design: 상단 색 채워지지 않는 오류 해결
  src/app/collection/page.css.ts
Labels: Fix, Design

#163 Fix: collection title
  public/images/fallback_backgroundImage.webp
  public/images/fallback_list.webp
  public/images/fallback_profileImage.webp
  public/images/fallback_renctangle.webp
  public/images/fallback_square.lg.webp
  public/images/fallback_square.sm.webp
  src/app/collection/[category]/page.tsx
  src/app/collection/locale.ts
  src/components/exploreComponents/ListsRecommendation.tsx
Labels: Fix, Enhance

#165 Feat: Update ReadMe - layout
  .prettierignore
  README.md
Labels: Docs

#173 Design: UI 수정
  public/icons/kakao_login_medium_narrow.svg
  public/icons/kakao_login_narrow.svg
  src/app/_api/list/getAllList.ts
  src/app/start-listy/_components/CategoryButton.css.ts
  src/app/user/[userId]/_components/Card.css.ts
  src/app/user/[userId]/_components/Profile.tsx
  src/components/login/LoginModal.tsx
Labels: Design

#175 Docs: ReadMe - 온보딩 gif update
  README.md
Labels: Docs

#177 Docs: Update ReadMe
  README.md
Labels: Docs

#180 Fix: 콜렉션, 마이페이지, 탈퇴하기, 프로필 설정 오류 해결
  public/icons/folder_food.svg
  src/app/account/_components/LanguageDropdown.tsx
  src/app/account/page.tsx
  src/app/account/profile/page.tsx
  src/app/account/withdraw/_component/WithdrawalHeader.tsx
  src/app/collection/page.tsx
Labels: Feat, Fix, Refactor
