Repository 8-Sprinters/ListyWave-front, pull requests merged in 2024-12, with the labels that each got.

#275 Refactor: 리스트 수정 에러처리
  src/app/list/[listId]/edit/page.tsx
  src/app/list/create/_components/StepThree.tsx
  src/lib/constants/toastMessage.ts
Labels: Fix

#278 Design: 글로벌 스타일 수정에 따른 전체 페이지 스타일 조정
  src/app/(home)/_components/FeedLists.css.ts
  src/app/(home)/_components/FeedLists.tsx
  src/app/(home)/_components/TrendingLists.css.ts
  src/app/(home)/_components/TrendingLists.tsx
  src/app/(home)/page.css.ts
  src/app/(home)/page.tsx
  src/app/account/page.css.ts
  src/app/account/page.tsx
  src/app/account/profile/page.css.ts
  src/app/account/profile/page.tsx
  src/app/account/withdraw/_component/WithdrawalHeader.tsx
  src/app/account/withdraw/page.css.ts
  src/app/account/withdraw/page.tsx
  src/app/collection/[folderId]/page.css.ts
  src/app/collection/[folderId]/page.tsx
  src/app/collection/page.css.ts
  src/app/layout.css.ts
  src/app/layout.tsx
  src/app/list/[listId]/_components/ListDetailOuter/Comments.css.ts
  src/app/list/[listId]/history/page.css.ts
  src/app/list/[listId]/history/page.tsx
  src/app/list/create/_components/Step.css.ts
  src/app/list/create/_components/StepOne.tsx
  src/app/list/create/_components/StepThree.tsx
  src/app/list/create/_components/StepTwo.tsx
  src/app/notification/page.css.ts
  src/app/notification/page.tsx
  src/app/start-listy/_components/CategoryButton.css.ts
  src/app/topics/_components/BottomSheet.css.ts
  src/app/topics/page.css.ts
  src/app/user/[userId]/(follow)/_components/Header.tsx
  src/app/user/[userId]/(follow)/follow.css.ts
  src/app/user/[userId]/_components/Content.css.ts
  src/app/withdrawn-account/page.css.ts
  src/components/BottomNav/BottomNav.css.ts
  src/components/BottomSheet/BottomSheet.css.ts
  src/components/BottomSheet/ver3.0/BottomSheet.css.ts
  src/components/Modal/Modal.css.ts
  src/components/NoData/NoData.css.ts
  src/components/NoData/NoDataComponent.tsx
  src/components/exploreComponents/RecommendedUsers.css.ts
  src/middleware.ts
Labels: Design

#283 홈 페이지 API 연동
  src/app/(home)/_components/FeedLists.css.ts
  src/app/(home)/_components/FeedLists.tsx
  src/app/(home)/_components/FollowButton.tsx
  src/app/(home)/_components/Header.css.ts
  src/app/(home)/_components/Header.tsx
  src/app/(home)/_components/HomeRecommendedLists.css.ts
  src/app/(home)/_components/HomeRecommendedLists.tsx
  src/app/(home)/_components/RecommendationFeed.tsx
  src/app/(home)/_components/RecommendedUsers.css.ts
  src/app/(home)/_components/RecommendedUsers.tsx
  src/app/(home)/_components/SearchBarArea.css.ts
  src/app/(home)/_components/SearchBarArea.tsx
  src/app/(home)/_components/Skeleton.css.ts
  src/app/(home)/_components/Skeleton.tsx
  src/app/(home)/_components/TopicsRecommendation.css.ts
  src/app/(home)/_components/TopicsRecommendation.tsx
  src/app/(home)/mock/mockdata.ts
  src/app/__page.tsx
  src/app/_api/home/getHomeRecommendedLists.ts
  src/app/_api/home/getRecommendedTopics.ts
  src/app/_api/home/getTrendingLists.ts
  src/app/search/_components/SearchBar.css.ts
  src/components/SearchBar/KeywordArea.css.ts
  src/components/SearchBar/KeywordArea.tsx
  src/components/SearchBar/index.tsx
  src/components/SimpleList/SimpleList.tsx
  src/components/exploreComponents/FeedLists.tsx
  src/components/exploreComponents/Header.css.ts
  src/components/exploreComponents/Header.tsx
  src/components/exploreComponents/ListsRecommendation.css.ts
  src/lib/constants/placeholder.ts
  src/lib/constants/queryKeys.ts
  src/lib/types/homeType.ts
  yarn.lock
Labels: Feat, Fix
