Repository 8-Sprinters/ListyWave-front, pull requests merged in 2024-04, with the labels that each got.

#215 Refactor: 프로필 설정 스켈레톤 직접구현 컴포넌트로 교체
  src/app/account/profile/_components/ImagePreview.tsx
  src/app/account/profile/_components/ProfileForm.css.ts
  src/app/account/profile/_components/ProfileForm.tsx
  src/app/account/profile/_components/ProfileSkeleton.tsx
  src/app/account/profile/page.tsx
  src/components/Skeleton/Skeleton.css.ts
  src/components/Skeleton/Skeleton.tsx
Labels: Feat, Enhance

#207 feat: 구글태그매니저(gtm) 스니펫 삽입
  src/app/intro/_components/Footer.tsx
  src/app/layout.tsx
  src/app/list/[listId]/_components/ListDetailInner/CollectButton.tsx
  src/app/list/[listId]/_components/ListDetailOuter/Comments.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/user/[userId]/_components/FollowButton.tsx
  src/components/BottomNav/BottomNav.tsx
  src/components/exploreComponents/FollowButton.tsx
  src/components/exploreComponents/Header.tsx
  src/components/floatingButton/PlusOptionFloatingButton.tsx
  src/components/login/LoginModal.tsx
  src/lib/utils/gtag.tsx
  src/lib/utils/gtm.tsx
Labels: Feat

#221 feat: 구글태그매니저(gtm) 스니펫 삽입 (#207)
  src/app/intro/_components/Footer.tsx
  src/app/layout.tsx
  src/app/list/[listId]/_components/ListDetailInner/CollectButton.tsx
  src/app/list/[listId]/_components/ListDetailOuter/Comments.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/user/[userId]/_components/FollowButton.tsx
  src/components/BottomNav/BottomNav.tsx
  src/components/exploreComponents/FollowButton.tsx
  src/components/exploreComponents/Header.tsx
  src/components/floatingButton/PlusOptionFloatingButton.tsx
  src/components/login/LoginModal.tsx
  src/lib/utils/gtag.tsx
  src/lib/utils/gtm.tsx
Labels: Feat

#213 Fix: intro 페이지 이미지 교체, 메이커스 이름 추가 (임시)
  public/images/section7_phone2.png
  public/videos/record_video.mp4
  public/videos/video_section3.mp4
  src/app/intro/_components/Footer.tsx
  src/app/intro/_components/MotionWrapper.tsx
  src/app/intro/_components/Section3.css.ts
  src/app/intro/_components/Section3.tsx
  src/app/intro/_components/Section7.tsx
Labels: Fix, Design

#219 Refactor: 온보딩페이지 UI/UX 개선 및 useOnClickOutSide 훅 로직 수정
  package.json
  src/app/start-listy/_components/CategoryButton.css.ts
  src/app/start-listy/_components/CreateListStep.tsx
  src/app/start-listy/_components/CreateNicknameStep.css.ts
  src/app/start-listy/_components/ListPreview.css.ts
  src/app/start-listy/_components/RegisterListTitle.tsx
  src/app/start-listy/_components/SkipButton.tsx
  src/app/start-listy/locale.ts
  src/app/start-listy/page.tsx
  src/components/BottomSheet/BottomSheet.tsx
  src/components/loading/Spinners.css.ts
  src/components/loading/Spinners.tsx
  src/hooks/useOnClickOutside.ts
  yarn.lock
Labels: Feat, Fix, Refactor, Design

#223 Refactor: [UI/UX 개선] 팔로우버튼, 콜렉트버튼 - optimistic UI 적용
  src/app/list/[listId]/_components/ListDetailInner/CollectButton.tsx
  src/app/list/[listId]/_components/ListDetailOuter/ListInformation.tsx
  src/app/user/[userId]/_components/FollowButton.tsx
  src/components/exploreComponents/FollowButton.tsx
Labels: Refactor

#222 Refactor: 리스트 상세 '이 타이틀로 리스트 생성하기' 비회원 접근 시 로직 수정
  src/app/list/[listId]/_components/ListDetailInner/Footer.tsx
  src/app/list/[listId]/_components/ListDetailInner/getBottomSheetOptionList.ts
  src/app/list/[listId]/locale.ts
Labels: Refactor

#226 Fix: GTM 태그 재삽입
  src/app/layout.tsx
Labels: Fix

#224 Chore: dev-ver2에서 dev 커밋 cherry-pick, 탐색 페이지 이슈 해결 시도
  public/images/section7_phone2.png
  public/sw.js.map
  public/videos/record_video.mp4
  public/videos/video_section3.mp4
  src/app/intro/_components/Footer.tsx
  src/app/intro/_components/MotionWrapper.tsx
  src/app/intro/_components/Section3.css.ts
  src/app/intro/_components/Section3.tsx
  src/app/intro/_components/Section7.tsx
  src/app/list/[listId]/_components/ListDetailOuter/Comment.css.ts
  src/app/list/[listId]/_components/ListDetailOuter/Comment.tsx
  src/app/list/[listId]/_components/ListDetailOuter/CommentForm.tsx
  src/app/list/[listId]/_components/ListDetailOuter/Comments.css.ts
  src/app/list/[listId]/_components/ListDetailOuter/Comments.tsx
  src/app/list/[listId]/_components/ListDetailOuter/Replies.tsx
  src/components/exploreComponents/TrendingLists.css.ts
  src/components/exploreComponents/TrendingLists.tsx
  src/hooks/useEnterKeyDown.ts
  src/store/useComment.ts
Labels: Fix, Chore

#229 Hotfix: 마이페이지 드롭다운 컴포넌트 수정(커스텀 훅 대신 useState로 관리)
  src/app/account/_components/LanguageDropdown.tsx
Labels: Fix
