Repository 8-Sprinters/ListyWave-front, pull requests merged in 2025-01, with the labels that each got.

#284 Notice 페이지 API 연동 및 컴포넌트 교체
  public/sw.js
  public/workbox-1bb06f5e.js
  src/app/_api/notice/getNotices.ts
  src/app/notice/NoticeList.css.ts
  src/app/notice/NoticeList.tsx
  src/app/notice/[noticeId]/NoticeDetail.css.ts
  src/app/notice/[noticeId]/NoticeDetail.tsx
  src/app/notice/[noticeId]/page.tsx
  src/app/notice/noticePage.css.ts
  src/app/notice/page.tsx
  src/app/notices/[noticeId]/NoticeDetail.tsx
  src/app/notices/[noticeId]/page.tsx
  src/app/notices/layout.tsx
  src/app/notices/mockdata.ts
  src/components/NoticeDetail/NoticeDetailContents.css.ts
  src/components/NoticeDetail/NoticeDetailContents.tsx
  src/components/NoticeDetail/NoticeDetailInfo.css.ts
  src/lib/constants/queryKeys.ts
Labels: Feat, Fix

#288 Feature: 팔로워 팔로잉 페이지 디자인 수정 및 확인 기능 추가
  src/app/list/[listId]/_components/ListDetailOuter/DeleteModalButton.tsx
  src/app/user/[userId]/(follow)/_components/Header.css.ts
  src/app/user/[userId]/(follow)/_components/Header.tsx
  src/app/user/[userId]/(follow)/_components/UserList.css.ts
  src/app/user/[userId]/(follow)/_components/UserList.tsx
  src/app/user/[userId]/(follow)/_components/mockData.ts
  src/app/user/[userId]/(follow)/follow.css.ts
  src/app/user/[userId]/(follow)/followers/page.tsx
  src/app/user/[userId]/(follow)/followings/page.tsx
  src/app/user/[userId]/_components/OptionToggleButton.tsx
  src/components/DeleteModal/DeleteModal.tsx
Labels: Feat, Design

#292 Fix: 리스트 생성,수정 오류 수정
  src/app/(home)/_components/TopicsRecommendation.tsx
  src/app/list/[listId]/edit/page.tsx
  src/app/list/create/_components/ItemAccordion.css.ts
  src/app/list/create/_components/ItemAccordion.tsx
  src/app/list/create/_components/StepOne.tsx
  src/app/topics/page.tsx
Labels: Fix
